# Generated by Django 5.1 on 2024-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
